apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: myharbor.apps.okd4.ktdemo.duckdns.org/mvp/mvp_ppon_sub_backend
  newTag: "20240514183556"
